global:
  scrape_interval: 15s

scrape_configs:
#--------- Node Exporter ---------#
  - job_name: "node-exporter"
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
        filters:
          - name: "tag:Name"
            values: ["webserver*"]
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: host


#--------- cAdvisor ---------#

  - job_name: "cadvisor"
    ec2_sd_configs:
      - region: us-east-1
        port: 8080
        filters:
          - name: "tag:Name"
            values: ["webserver*"]
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: host
